### ISSUE TITLE
老哥，限制登入错误次数用security怎么实现的

### ISSUE THREAD

**Issue by LeeyouJay** [ZeroWdd/manager-system#2]

**Comment by ZeroWdd** [comment]
抱歉，spring security默认是没有限制的。你可自行开启，并且网上有相关教程。

**Comment by ZeroWdd** [comment]
> _No description provided._

抱歉，spring security默认是没有限制的。你可自行开启，并且网上有相关教程。

**Comment by ZeroWdd** [comment]
> _没有提供描述。_

抱歉，spring security至少是没有限制的。你可自行开启，并且网上有相关教程。
